<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Local contracts</name>
   <tag></tag>
   <elementGuidId>26d42012-1adf-4cde-b5d4-ca2805564014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b1-Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f6756bc-c9fc-40c9-999c-c8b50e207b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-top-title heading1 ph font-extra-bold </value>
      <webElementGuid>b782cc22-c5b6-4fc6-84a0-09de0a2280bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-Title</value>
      <webElementGuid>b58e3c1d-aced-4bcf-8be1-23fbc1840971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Local contracts</value>
      <webElementGuid>a5e4600f-5550-4fb6-a0bb-e5aa21144198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-Title&quot;)</value>
      <webElementGuid>e1008578-52ef-4676-a4f2-c9cdfd550887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4c2c8fc-2b11-4cfb-8d75-9161067eae23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-top-title heading1 ph font-extra-bold </value>
      <webElementGuid>d377d95c-cabb-427f-90c9-12e2e133e8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-Title</value>
      <webElementGuid>0c274d42-2bb0-407f-b616-ae22819c5551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Local contracts</value>
      <webElementGuid>a512859a-c706-4a36-9a99-de49d5cab03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-Title&quot;)</value>
      <webElementGuid>786580c8-d913-4db6-b6fd-b040420e6d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b1-Title']</value>
      <webElementGuid>b4d7b2ec-5dab-4596-9f3c-0bd41fd1c7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContentWrapper']/div/div/div[2]/div</value>
      <webElementGuid>97ccc897-2c07-4bff-9c6a-5d6cce860f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Travels'])[1]/following::div[4]</value>
      <webElementGuid>d655cbe1-842f-47db-abf3-48c83f3a20fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignments'])[1]/following::div[6]</value>
      <webElementGuid>8e3f342e-cfee-4b5e-86ac-9224b4318c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id'])[1]/preceding::div[24]</value>
      <webElementGuid>2fd47d1e-c966-477e-9905-0ed1f386fa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Name'])[1]/preceding::div[24]</value>
      <webElementGuid>5167067a-46af-4a80-8e80-7069345d8555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Local contracts']/parent::*</value>
      <webElementGuid>2ba1b699-0f06-422d-a745-f7dcb81a26e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>b920fc9d-8ae2-4f8f-8461-33029c278586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b1-Title' and (text() = 'Local contracts' or . = 'Local contracts')]</value>
      <webElementGuid>5d5d8e74-470b-4a97-acf1-25a21b2b6cd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
