<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__icon transformTransition fa fa-angle-down fa-2x</name>
   <tag></tag>
   <elementGuidId>1e389563-6f53-47a9-afaf-dcccfcadbfe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b35-DropdownList_Cnt']/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d20772d6-485f-48f5-92d3-685fabe35327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon transformTransition fa fa-angle-down fa-2x</value>
      <webElementGuid>960a6cde-a912-4362-b840-f5cbfb29bc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b35-DropdownList_Cnt&quot;)/div[2]/i[@class=&quot;icon transformTransition fa fa-angle-down fa-2x&quot;]</value>
      <webElementGuid>7deaf730-c156-4eb5-9627-cbcbc7fc4cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e8cac305-db3c-4fdd-94e6-210ba7be5840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon transformTransition fa fa-angle-down fa-2x</value>
      <webElementGuid>1969dec1-a77a-487c-9343-1159aa63bb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b35-DropdownList_Cnt&quot;)/div[2]/i[@class=&quot;icon transformTransition fa fa-angle-down fa-2x&quot;]</value>
      <webElementGuid>1205e4de-345a-485f-8f8c-61958d532d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b35-DropdownList_Cnt']/div[2]/i</value>
      <webElementGuid>747407ae-b26a-49db-99f1-856036731210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/i</value>
      <webElementGuid>a9ba171c-9ef3-4b92-9ee5-d01538b6e63e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
