<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_New Scenario 2_icon transformRotate trans_1383d3</name>
   <tag></tag>
   <elementGuidId>8359ab14-cc66-405f-b9cc-59fcc1d9f27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.transformRotate.transformTransition.fa.fa-angle-down.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b35-DropdownList_Cnt']/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7165364c-90ce-46a7-86fd-c80169ab95a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon transformRotate transformTransition fa fa-angle-down fa-2x</value>
      <webElementGuid>bed77995-c8a3-4bb2-9bef-9ad34110828a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b35-DropdownList_Cnt&quot;)/div[2]/i[@class=&quot;icon transformRotate transformTransition fa fa-angle-down fa-2x&quot;]</value>
      <webElementGuid>4a46461e-1e39-4d26-9b23-cbc96c940c65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b35-DropdownList_Cnt']/div[2]/i</value>
      <webElementGuid>27d83061-a1e6-4b71-a6e5-0446268dd62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div[2]/i</value>
      <webElementGuid>351c7c6c-4ef2-483e-914e-957382f807cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
