<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_Input_EmployeeLastName</name>
   <tag></tag>
   <elementGuidId>3504134c-44d0-46b1-9477-76d86cb236e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_EmployeeLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_EmployeeLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d36e59f0-982f-460f-adee-681da5ba3ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>940b863d-ca7f-406a-b41b-5cf77ab27490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2ce129c-9c08-490e-9125-29ad54e2737c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c935b834-1d77-441f-86ba-d849202147b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Input_EmployeeLastName_DescribedBy</value>
      <webElementGuid>50c976a4-2cd9-446f-980e-b39729614b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Bino</value>
      <webElementGuid>035a5a30-478f-4181-ae62-049b6e373a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_EmployeeLastName</value>
      <webElementGuid>3077c62c-83ff-41ff-a99a-69c61e615834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_EmployeeLastName&quot;)</value>
      <webElementGuid>8eeeb3e8-e595-4e34-9752-8942da783f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_EmployeeLastName']</value>
      <webElementGuid>7408f0fb-d28e-4b2f-b5c3-b6a61cbba7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b11-Input']/span/input</value>
      <webElementGuid>8147251b-d18e-4937-a754-e0a84a3c2a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>bea4dbeb-88bf-4a94-8136-2f255bf03be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_EmployeeLastName']</value>
      <webElementGuid>d0499365-bb18-499d-82a0-d92d3f0db706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
