<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Academic Degree_Input_AcademicDegree</name>
   <tag></tag>
   <elementGuidId>f9dfa7ec-103e-43da-a1ed-23e3da5845c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_AcademicDegree</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_AcademicDegree']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15486ba7-ed31-474a-9057-01e97bcf2c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>fb12343e-c852-4308-a45c-3cc502209cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48e5b44e-1522-45f0-826b-d469d73fed27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b98c1d72-9a19-4e5c-a5d9-d1d3ad3ba345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Input_AcademicDegree_DescribedBy</value>
      <webElementGuid>36a8100d-40a1-4263-9083-18e35390f31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3b9adffc-fccd-4317-933c-c7a934f9ad28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_AcademicDegree</value>
      <webElementGuid>01468c6c-6286-4b41-91ae-9ef39b4b5932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_AcademicDegree&quot;)</value>
      <webElementGuid>a0b6031e-0fa3-4901-aeb8-f5d44d876934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_AcademicDegree']</value>
      <webElementGuid>5740351d-5ba0-4f32-bd17-0caa47f3f055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b13-Input']/span/input</value>
      <webElementGuid>b2be95c3-b599-4146-b8d8-47acad518a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/span/input</value>
      <webElementGuid>bfb092ac-a141-4b8b-822a-e3284f7855ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_AcademicDegree']</value>
      <webElementGuid>d5c3de78-fffa-4ab2-ab5f-024af5705793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
