<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_Radio_SocialSecurity</name>
   <tag></tag>
   <elementGuidId>71f66512-5630-4fc7-bbc9-21b4723804d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RadioButton4-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadioButton4-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e8e8e95-ec96-4607-a1fd-6b37d150d28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bd05b27c-c93a-4da7-a5ac-0bb79ca2cf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadioButton4-input</value>
      <webElementGuid>7ccac383-68fc-46cf-9ac1-86bcad53d700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>7ca538d3-b730-49fc-bb92-a5be2845e8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Radio_SocialSecurity</value>
      <webElementGuid>4b90e251-94df-4fd5-882d-c403905865ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>e2b4903b-d8c8-40e9-b1d9-53a15fa26db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadioButton4-input&quot;)</value>
      <webElementGuid>542cd0da-d959-47d2-a97d-6367e52d1fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadioButton4-input']</value>
      <webElementGuid>e703825c-f24a-4c32-b671-4cc419aef218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadioButton4']/input</value>
      <webElementGuid>c1383a8b-eac4-4380-b2aa-121950c12387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>5f7caa10-5936-42a8-a9ae-ed76c0bf2154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'RadioButton4-input' and @name = 'Radio_SocialSecurity']</value>
      <webElementGuid>bc59f67f-e06e-4204-bebf-d23eb50dfa15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
