<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Citizen</name>
   <tag></tag>
   <elementGuidId>0529e362-c5e0-474c-b2b7-c9132ae56414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l4-89_0-ListItem2 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l4-89_0-ListItem2']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Citizen' or . = 'Citizen')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b52d3cd7-f898-4cdf-8ddd-d8c18de3d152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Citizen</value>
      <webElementGuid>2b2250fc-2498-46bd-8e31-73e615f6c42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l4-89_0-ListItem2&quot;)/span[1]</value>
      <webElementGuid>97336bf3-7a3a-46d2-8ca5-b891b1393437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l4-89_0-ListItem2']/span</value>
      <webElementGuid>a147699a-0139-4d61-8096-4e8bbe6f71b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ale Hop'])[1]/following::span[2]</value>
      <webElementGuid>df3de804-e62d-46c7-b56a-dd15a8d3efef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[3]</value>
      <webElementGuid>39104d4d-6133-4c16-8562-b1371d429b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Contract City'])[1]/preceding::span[1]</value>
      <webElementGuid>fb008962-9e14-4679-8408-9f86a6225ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Contract Payroll Identifier'])[1]/preceding::span[3]</value>
      <webElementGuid>90efcf2d-fda8-4f13-a3ac-824b9705fe6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Citizen']/parent::*</value>
      <webElementGuid>587a3c0e-9a24-489f-b57e-0b2deee3c23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[2]/div/div/span</value>
      <webElementGuid>7ae96d68-9a57-4b73-aee4-60a52ecb9085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Citizen' or . = 'Citizen')]</value>
      <webElementGuid>920e7fd1-5d7c-4cdb-a3a1-8124bca7e3d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
