<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit employee</name>
   <tag></tag>
   <elementGuidId>958668b6-0765-45a6-8d8d-f5f25fd43b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l1_0-54_0-b11-Option > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l1_0-54_0-b11-Option']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac11a275-0f3f-4952-8620-55ef3a754ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f30da972-972e-4609-9528-fdd2b4bb1e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit employee</value>
      <webElementGuid>2942bbf7-3472-4ebb-b704-da2012031068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-54_0-b11-Option&quot;)/a[1]</value>
      <webElementGuid>fabbbd8c-46a3-4875-ae72-c556e33efde8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l1_0-54_0-b11-Option']/a</value>
      <webElementGuid>510cb9d6-c0c2-4430-b1f6-7b53de389404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit employee')]</value>
      <webElementGuid>30a6e435-7d0e-48ce-b386-714b17c63983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Employee'])[1]/following::a[1]</value>
      <webElementGuid>7dc2921c-6ad7-44a3-a342-b761f92d22ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature to be developed'])[2]/following::a[1]</value>
      <webElementGuid>ae7ee65f-4bd9-49e5-9a30-c58d602c4623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'l1_0-54_0-b11-Option', '&quot;', ')/a[1]')])[1]/preceding::a[1]</value>
      <webElementGuid>58016a65-2f80-40af-827a-46cee5e04684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit employee']/parent::*</value>
      <webElementGuid>a9cf7d07-b2ab-4868-8e89-d91b7c730a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>2340eb9b-a0bf-4155-b812-73610409dfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>708ac059-ac7e-40bc-9d01-53f72aed39b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Edit employee' or . = 'Edit employee')]</value>
      <webElementGuid>46ded7ce-dcbf-4fb4-80e6-0e18764adcf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
