<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_of_b12-b1-LastPage_Btn</name>
   <tag></tag>
   <elementGuidId>9f7e82c8-11ee-41b8-bd26-4a50ee8757ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b12-b1-LastPage_Btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b12-b1-LastPage_Btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a1a2024-6721-48ff-87e1-e1d0d9989bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagination-button</value>
      <webElementGuid>e33b6859-2e50-4281-8b68-fcb0ea4ad7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6a57666-156b-4ada-8b13-5ffe0b495bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>go to last page</value>
      <webElementGuid>9d724d1d-94b7-400c-8bf6-66a4c4a10cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b12-b1-LastPage_Btn</value>
      <webElementGuid>6069005e-867d-467b-8ac2-06c24902bcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-b1-LastPage_Btn&quot;)</value>
      <webElementGuid>6739a1b6-9c8f-4dcb-aa21-d80d97ad870c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b12-b1-LastPage_Btn']</value>
      <webElementGuid>9d3bde7a-7b11-4571-9d2a-c8d681dd1239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b12-b1-PaginationContainer']/div/button[4]</value>
      <webElementGuid>f4437389-74ee-451f-ad9b-1f22b1c570d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[1]/following::button[4]</value>
      <webElementGuid>fe6265a3-5425-4fdc-ab1b-a680603bc408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[4]</value>
      <webElementGuid>9cddba0c-6c1b-4f33-a52e-c1bf1a28f79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature to be developed'])[1]/preceding::button[1]</value>
      <webElementGuid>20304376-5135-47ff-bfed-dc36a0eb775a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature to be developed'])[2]/preceding::button[1]</value>
      <webElementGuid>ab7289d7-815a-473d-951a-fa3c863df3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>6be48731-6904-4402-b506-0eb497499b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b12-b1-LastPage_Btn']</value>
      <webElementGuid>392a0063-d322-4667-b75e-0880242f3b34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
