<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Client_DevClient</name>
   <tag></tag>
   <elementGuidId>7cb3cbee-3d42-4e6b-b69f-4b71c0d4684b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l1_0-18_3-ClientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='l1_0-18_3-ClientName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'ClientName') and (text() = 'DevClient' or . = 'DevClient')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClientName</value>
      <webElementGuid>fb374871-2a84-4cf8-a9be-3fb64a307b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevClient</value>
      <webElementGuid>f086b831-812b-42e3-a952-01d63664261b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClientName</value>
      <webElementGuid>b4371350-89a0-46f2-bec6-c7a622763dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevClient</value>
      <webElementGuid>450b4c7c-1cd1-4ca1-ae37-a130997964a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l1_0-18_3-ClientName']</value>
      <webElementGuid>7b9a08f3-03af-43f5-a003-43ac7106060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ResultsTable']/tbody/tr[4]/td[2]/a/span</value>
      <webElementGuid>4a283727-f681-47de-927a-c31656559824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Test'])[1]/following::span[2]</value>
      <webElementGuid>d8bcb0ef-55b2-4d39-bc4b-87cfff14d811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClientNew'])[1]/following::span[4]</value>
      <webElementGuid>64ba71fc-1a21-4d5b-b991-e81431d00e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/preceding::span[1]</value>
      <webElementGuid>56912f20-734e-423b-8a38-16f53da2c3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[3]</value>
      <webElementGuid>87d86f69-0626-4402-a5eb-14ed74ac4d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a/span</value>
      <webElementGuid>00287ff3-9837-40c6-9636-3b1d07f0c24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l1_0-18_3-ClientName' and (text() = 'DevClient' or . = 'DevClient')]</value>
      <webElementGuid>a5a1e4b6-fbd5-4939-a735-283eb3e14e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l1_0-18_0-ClientName']</value>
      <webElementGuid>eb520db1-27ff-4982-944a-645fcc048705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ResultsTable']/tbody/tr/td[2]/a/span</value>
      <webElementGuid>df65d885-fa5a-4556-a1c7-ce33d592895a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[3]/following::span[3]</value>
      <webElementGuid>9514de1d-a654-4c9a-8b81-4da93ad8a314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imports'])[1]/following::span[3]</value>
      <webElementGuid>d0ed83b4-8984-4f13-8002-b289a4c32a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/span</value>
      <webElementGuid>be7966ca-abe4-45a4-8368-21774e20459a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l1_0-18_0-ClientName' and (text() = 'DevClient' or . = 'DevClient')]</value>
      <webElementGuid>d21dd1c5-35f1-4efb-8377-ff1fc5b04f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
