<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Portugal_l1_0-54_0-b11-more</name>
   <tag></tag>
   <elementGuidId>cbdf1701-ead8-40fc-9b4e-f82148c814b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l1_0-54_0-b11-more</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l1_0-54_0-b11-more']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c054f15c-7d6f-4399-a440-e6f2115c7125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-block</name>
      <type>Main</type>
      <value>Main_Resources.GCM_Icons</value>
      <webElementGuid>b4509ce1-3654-4200-bfd2-6ff2567d4de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSBlockWidget</value>
      <webElementGuid>77b73b85-f13f-4034-babd-0c7b40ca9ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l1_0-54_0-b11-more</value>
      <webElementGuid>0bf4c950-5eb0-46d6-81e3-e42659ae33be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-54_0-b11-more&quot;)</value>
      <webElementGuid>88c59f1c-a8a6-4a65-812f-c6eddadf3cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='l1_0-54_0-b11-more']</value>
      <webElementGuid>d2b57ca9-3789-497e-ba24-d139c12c0fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l1_0-54_0-$b11']/div/div/div</value>
      <webElementGuid>abfbb9d0-5b04-463f-ae00-d192ac3c43ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portugal'])[1]/following::div[4]</value>
      <webElementGuid>826db2b5-f714-4d09-a3aa-79c5f7508bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bino, Joaquim'])[1]/following::div[4]</value>
      <webElementGuid>4f4eae89-83e6-4285-901f-3fa1d3b428ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/preceding::div[1]</value>
      <webElementGuid>06e51d04-8216-49e6-9e36-bcdf3656b70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::div[5]</value>
      <webElementGuid>1118284d-b253-4912-9da6-4e9231918b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/div/div</value>
      <webElementGuid>819fb143-cb3f-4771-9df2-6c0d27574602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'l1_0-54_0-b11-more']</value>
      <webElementGuid>40b2edbe-bd3a-4310-a402-977fb8628a41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
