<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New Scenario 2</name>
   <tag></tag>
   <elementGuidId>05b55335-1dda-4ad2-81dd-73e1a445a6c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l6-91_0-ListItem6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l6-91_0-ListItem6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b52821e-498a-4252-9b8d-527db88a5aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>a80228c8-25f2-4e66-87e3-7d4bbfda0249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l6-91_0-ListItem6</value>
      <webElementGuid>5b679a46-11c8-4972-9fb4-989c5e8c4bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Scenario 2</value>
      <webElementGuid>ef1dde32-1962-4fc6-9714-6e08db8fcaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l6-91_0-ListItem6&quot;)</value>
      <webElementGuid>2078dc12-a4ee-49c9-b27b-93ac5b47fd23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='l6-91_0-ListItem6']</value>
      <webElementGuid>9da4c5ea-4437-46b9-b80b-2e8fb7ef6522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b35-Ph_List']/div/div</value>
      <webElementGuid>3c66c60e-ecff-48a8-a88f-4f3171979b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[14]</value>
      <webElementGuid>77a7bfc9-2332-4054-b1f8-1c3a391b3c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Contract Tax Scenario'])[1]/following::div[15]</value>
      <webElementGuid>4218f781-b45b-4733-89de-4b0961992236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Scenario PT 1'])[1]/preceding::div[1]</value>
      <webElementGuid>67da0b8e-00d8-4089-9677-237c7acdd331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div[2]/div/div</value>
      <webElementGuid>1e201011-6c54-471b-84b0-9fae2dc9d9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'l6-91_0-ListItem6' and (text() = 'New Scenario 2' or . = 'New Scenario 2')]</value>
      <webElementGuid>9bc95448-e10f-457e-8571-c6ef4c2e7a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
