<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wico</name>
   <tag></tag>
   <elementGuidId>b82f0d8b-a511-4318-a300-f13ac28f1308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l4-82_1-ListItem2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l4-82_1-ListItem2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cc718e4-f03f-4f9f-8e4c-0e05e012f8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>bd8e2470-425a-4d2f-abd9-71f346a8dcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l4-82_1-ListItem2</value>
      <webElementGuid>8358e75b-b3c6-431a-a53a-4246e257fd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wico</value>
      <webElementGuid>6bc8e9b7-48d8-481c-abe1-ebc4997b0369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l4-82_1-ListItem2&quot;)</value>
      <webElementGuid>152edd9d-464a-46fc-8a90-df7217e09a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58c10958-a9f3-46bc-a7c5-97f44847ad0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>5d53a6db-c481-4bf6-8919-14213773217a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l4-76_1-ListItem2</value>
      <webElementGuid>1acaf00b-1186-43ea-ae97-3ee9763bc5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wico</value>
      <webElementGuid>da25ee29-3421-4bec-9390-53a9f622251a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l4-76_1-ListItem2&quot;)</value>
      <webElementGuid>44d68e7d-4661-4847-ba68-dcbf86e25328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>306a8da3-2ad1-4600-8e88-5f061a4426cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>10831204-b3d1-415c-addf-87280234035b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l4-76_1-ListItem2</value>
      <webElementGuid>beeb8723-1431-42eb-8d3f-d22f899a21c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wico</value>
      <webElementGuid>757d196d-458c-45cf-8210-27dd728ffa8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l4-76_1-ListItem2&quot;)</value>
      <webElementGuid>7b9cc6dd-c5f0-45c4-b279-a25aceb9bc7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='l4-82_1-ListItem2']</value>
      <webElementGuid>d48933b0-71ea-444b-a343-673e660c782b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b30-Ph_List']/div/div[2]</value>
      <webElementGuid>5999b3f5-2210-4586-bb06-15d7c01b1ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ale Hop'])[2]/following::div[1]</value>
      <webElementGuid>80df7377-a9f7-4377-9576-bf4f8e51601a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ale Hop'])[1]/following::div[13]</value>
      <webElementGuid>74e185d1-5073-4e4e-a49f-16a721f7019e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mercedes'])[1]/preceding::div[1]</value>
      <webElementGuid>5e8eebea-66c3-446f-9775-484a10b18750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>13e9d801-3708-4b1b-8c9b-77996990d35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'l4-82_1-ListItem2' and (text() = 'Wico' or . = 'Wico')]</value>
      <webElementGuid>f5388ec6-d752-45ea-a324-c3e418df0fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='l4-76_1-ListItem2']</value>
      <webElementGuid>edc5f89e-8179-446e-a6aa-c219d3a243d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'l4-76_1-ListItem2' and (text() = 'Wico' or . = 'Wico')]</value>
      <webElementGuid>1ef69869-d7a3-4305-9f69-c235a1d67958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
