<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_of_GCM-icons icon-last_page text-neutral-_0c25de</name>
   <tag></tag>
   <elementGuidId>5c264ac2-260e-491f-8ea1-86a070d165c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.GCM-icons.icon-last_page.text-neutral-6.fa-24.font-bold.fa.fa-flag.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b12-$b5']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2b3abc5e-546b-4655-9a61-ef22f18926cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>2001232c-e455-4bdd-9102-35e15ca77509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>b99fa97f-7c1f-465c-9e08-a4473372ca6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d3e878f0-59cd-43d6-be5f-38e5a4e904fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>83c699b7-4828-4b5b-8085-8f42e58e49fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>e5d5d224-a16c-4c1f-ba20-6c9ee6002f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ce064dc9-3922-4f00-a47c-23c54675d9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>13ec1e12-eb87-4eb5-aa84-3618cfcea2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>781f9e73-b54c-4901-a179-3d542ce60bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7ba716a4-16cb-4241-bf38-252ea41bedb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>ae97d193-9d04-4373-8770-315d1919adc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>c6e8f72d-0138-4ffe-ad13-b3f847b69103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3e1f7843-b48c-432d-9d2f-603c7ecf2234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>6e404ca1-f93d-42ce-a0ad-0618f79cdde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>d765a30f-dbc3-42b5-8f44-d22222e45339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a84f140b-80aa-44f8-b824-de8f121bb644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>3a65d677-8456-4026-acad-66fa613c637c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>20784105-4f0e-4fc8-b20b-4b620b03087d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>314d7ce7-3810-4933-b0d4-314dc2ab4101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>ea52cf52-cbc8-4091-b60d-c91ea6f098bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>953f7260-fb24-4235-b26a-336beb364848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e3714efa-665b-4205-8c01-50d5aff7ea60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>6bc2b2dc-cfbc-4801-b600-66b4c00b4955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>a2dd75e5-aeaa-4378-a22b-50ccfefef168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b5263e59-c9c8-4236-90b0-825046741b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>7b853001-067a-4ca4-825a-921f21671758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>4837ecd5-e153-4711-a95a-e043a4c71dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4901bf9e-0c75-4b2e-b5a1-f32f62233978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>93a5fc38-9297-499d-a206-a1f9d1165c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>f3224515-32cc-40fe-9d2c-ecd55b270c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c295bbde-7e95-44dc-800d-561960f26a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>4adab9e3-e896-448f-9be4-48d262bafdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>d8273f4e-0bf4-4e8c-9d7f-41b75077c7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2241fb93-0617-45ae-8b65-7a31d855a226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>497f74f8-36dd-4d58-9131-5d70c2d55c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>07c9ce5f-5434-403c-a045-2508cd013a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>513634e7-053c-4796-9960-f433a4309597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>482ea249-6804-4ba9-925e-d408efe7f6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b5&quot;)/i[@class=&quot;GCM-icons icon-last_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>79eb08af-44c9-4890-9ee4-ca918fe63537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b12-$b5']/i</value>
      <webElementGuid>34edbcbc-5b49-491c-bc48-b949ef387504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[1]/following::i[4]</value>
      <webElementGuid>ee12cc3e-0db7-4fa2-abd7-71b5e6109fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::i[4]</value>
      <webElementGuid>94f8a70f-1c01-4f4e-9ce7-b480e6d90735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature to be developed'])[1]/preceding::i[1]</value>
      <webElementGuid>7e9272fd-5d61-496e-a56a-61c43d3a208b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature to be developed'])[2]/preceding::i[1]</value>
      <webElementGuid>a13b28ac-67ec-4825-b2d8-f8e84f47f41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/div/div/i</value>
      <webElementGuid>26ededec-0145-4961-9502-679778624759</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
