<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Id_EditedLocalContract_David</name>
   <tag></tag>
   <elementGuidId>d8ed2616-2ca5-49e1-8586-b3778aeaa08a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'CompanyId') and (text() = 'IDEditorLocalContract_David' or . = 'IDEditorLocalContract_David')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyId</value>
      <webElementGuid>4a4b108b-99a0-4620-9cf0-4c95cca00fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IDEditorLocalContract_David</value>
      <webElementGuid>4057d5db-e605-499f-acc4-ccb3690227ce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
