<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee ID_Input_EmployeeId</name>
   <tag></tag>
   <elementGuidId>dfdf6af3-0ef2-492c-8f6d-e42bcc7445ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_EmployeeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_EmployeeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>850ae071-521d-4148-a196-57577d3ecb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e4697d40-1d74-47d6-bc2e-2d606da9ba86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b302d7fd-20ff-4ba3-b9e4-d5fce199b8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c486a262-6658-4d39-99d9-07c52007ef80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Input_EmployeeId_DescribedBy</value>
      <webElementGuid>4170d865-bb4c-4b8e-9ecc-3c36033e54d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>51dedbe0-c8fa-4062-ad06-0d747bea2e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_EmployeeId</value>
      <webElementGuid>9ae627f7-ba3a-4784-97be-55b31f60bdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_EmployeeId&quot;)</value>
      <webElementGuid>5b2bd7bb-abb1-4bc6-a1b2-f9da505d8537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_EmployeeId']</value>
      <webElementGuid>f3dfbea1-4ffb-4da6-be12-a5bb3ed08868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b10-Input']/span/input</value>
      <webElementGuid>ea98becb-b2d2-4c1c-b75d-c1e908d694b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9d3aaada-4fd6-47ed-b623-4006bcc88521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_EmployeeId']</value>
      <webElementGuid>ee95139d-7750-4019-94a5-5e872c1cd6b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
