<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Local Contract Without termination da_f61511</name>
   <tag></tag>
   <elementGuidId>3b9e9b56-ee87-4d5c-87af-893f9bf8b766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RadioButton1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RadioButton1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7957124d-3c7d-48ea-82f2-4d977c8a92d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>42b96e9e-56da-4436-851b-795e8cf1e4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RadioButton1-input</value>
      <webElementGuid>14b96a00-a35c-4d81-9126-e6f34e51af6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>08c7648c-7f50-40c6-a973-eaf88e6639fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Radio_WithoutTerminationDate</value>
      <webElementGuid>dc100219-dbd7-4384-bcd1-af66fb5baf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>95186202-799f-42ee-9c0b-41ed4bb00214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RadioButton1-input&quot;)</value>
      <webElementGuid>b917231d-31c0-4ace-960f-6f196f6f7840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RadioButton1-input']</value>
      <webElementGuid>e7809566-1329-4d1c-b4e8-2eb6b32ee5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RadioButton1']/input</value>
      <webElementGuid>80dd2fd7-2abc-495e-84b0-19225afd7351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0c3851c0-a777-40d4-8cc3-df5a95cddec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'RadioButton1-input' and @name = 'Radio_WithoutTerminationDate']</value>
      <webElementGuid>8b793be6-d7c4-4950-a992-a2eb3b9fe6a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
