<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Employees</name>
   <tag></tag>
   <elementGuidId>d5454751-42f1-44e7-8945-3a54e9c294aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-l2-44_2-NavigationItemName_Expr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-b1-l2-44_2-NavigationItemName_Expr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a5ca518-a3b6-47b1-b44f-d08329506e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-l2-44_2-NavigationItemName_Expr</value>
      <webElementGuid>3dc84be6-8e27-4add-9a7a-9ba16c0b5cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>c4ec59d9-b152-4966-890d-cd8fc07d24ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b1-l2-44_2-NavigationItemName_Expr&quot;)</value>
      <webElementGuid>055bac83-fb1a-44e6-8ea3-90001c66ade2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-b1-l2-44_2-NavigationItemName_Expr']</value>
      <webElementGuid>c7b976e1-21f5-4575-8ba8-5c8ffde182ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-b1-l2-44_2-NavigationItemName_link']/span</value>
      <webElementGuid>102f02db-f0df-47e8-ae80-8c3046e7f35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::span[1]</value>
      <webElementGuid>8119e92c-8a72-41fa-bc64-82e5e633d307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[2]</value>
      <webElementGuid>a314750d-8288-4784-92aa-59f26acee9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Contracts'])[1]/preceding::span[1]</value>
      <webElementGuid>0af6747f-cc3e-46ee-acd5-f38439a65da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignments'])[1]/preceding::span[2]</value>
      <webElementGuid>1024b508-c884-47ec-8b5d-5861433d38b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employees']/parent::*</value>
      <webElementGuid>2c2336e8-bdcf-46c0-b87f-98a6b7a51e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/div[3]/div/a/span</value>
      <webElementGuid>bf3fc8f8-ffce-42c8-a690-88f07e306be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-b1-l2-44_2-NavigationItemName_Expr' and (text() = 'Employees' or . = 'Employees')]</value>
      <webElementGuid>96124136-2230-4323-8982-5bd7e1ca564a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
