<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DevClient</name>
   <tag></tag>
   <elementGuidId>2a98f6ef-4147-4087-bf72-0d3b6996e5df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l1_0-18_4-ClientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='l1_0-18_4-ClientName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddb184a2-9712-43b7-8c7e-6c8b1788e4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>7e902ccb-4108-4401-b892-f839996c63ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l1_0-18_4-ClientName</value>
      <webElementGuid>2e0efca6-484f-4abc-8646-b1d7b0b6bc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevClient</value>
      <webElementGuid>07242018-6d73-489e-b2e6-06d3ed22a82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-18_4-ClientName&quot;)</value>
      <webElementGuid>47636161-04f8-4898-8110-c709e50d30ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l1_0-18_4-ClientName']</value>
      <webElementGuid>55e1f943-c70e-4a8a-a01a-509e4b0f56f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ResultsTable']/tbody/tr[5]/td[2]/a/span</value>
      <webElementGuid>fca381ba-8404-43b9-aabf-c7c962899f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Test'])[1]/following::span[2]</value>
      <webElementGuid>e0be6243-6d24-4ad0-bbde-226718fc19ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClientNew'])[1]/following::span[4]</value>
      <webElementGuid>82bfb4f2-8d18-4beb-a622-ad8b8b2495b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/preceding::span[1]</value>
      <webElementGuid>1d053ba6-c182-4b80-8d85-cab234f2df7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[3]</value>
      <webElementGuid>14ac8671-f635-4c30-97c8-e41d1b4544dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/a/span</value>
      <webElementGuid>11d22c9b-d825-4267-b6f6-c83ab88b7a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l1_0-18_4-ClientName' and (text() = 'DevClient' or . = 'DevClient')]</value>
      <webElementGuid>14d8c192-c63c-49ea-9c26-873b344d5148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
