<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Local Contract City_font-size-base fon_13b141</name>
   <tag></tag>
   <elementGuidId>1bf8873a-d340-4c89-a496-0133d313419b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b32-DropdownList_Cnt > span.font-size-base.font-extra-bold.text-neutral-10.text-align-left.OSFillParent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b32-DropdownList_Cnt']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd549191-c30f-4f3e-b062-5e873cc4d870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-size-base font-extra-bold text-neutral-10 text-align-left OSFillParent</value>
      <webElementGuid>3d062210-eb3e-4cc8-8222-b5750017ad33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b32-DropdownList_Cnt&quot;)/span[@class=&quot;font-size-base font-extra-bold text-neutral-10 text-align-left OSFillParent&quot;]</value>
      <webElementGuid>484448cd-d029-432e-b0f4-930689d91c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b927b514-bfde-4709-9ec7-92770889986f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-size-base font-extra-bold text-neutral-10 text-align-left OSFillParent</value>
      <webElementGuid>b47b42a1-86c2-4585-9135-c4fa10a699b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b32-DropdownList_Cnt&quot;)/span[@class=&quot;font-size-base font-extra-bold text-neutral-10 text-align-left OSFillParent&quot;]</value>
      <webElementGuid>463834bc-0bf3-4cf6-9acb-29b10ea5e3b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b32-DropdownList_Cnt']/span</value>
      <webElementGuid>bda96b9f-2fee-4d46-a6a7-638993f2e7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/div[2]/span</value>
      <webElementGuid>380e0551-a7cd-45c3-888a-fc8d160e3ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
