<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TesteDavid</name>
   <tag></tag>
   <elementGuidId>3d1b8d68-9236-47c5-8189-74a8d3f62f4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#l1_0-5_0-ClientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='l1_0-5_0-ClientName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d53764c-2427-4a6c-a633-bf1ee56fac7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>ce69ed2c-8f3d-4d83-a32a-aecce32d2d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l1_0-5_0-ClientName</value>
      <webElementGuid>be2a2158-c66e-476f-b6ae-6453839de25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TesteDavid</value>
      <webElementGuid>47ff3236-d484-4218-bead-2ff0e2ffaeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-5_0-ClientName&quot;)</value>
      <webElementGuid>c204bb46-e180-4da2-8eae-634e47e68c0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l1_0-5_0-ClientName']</value>
      <webElementGuid>54e59f0f-f0d0-4d61-af63-36f16403545f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ResultsTable']/tbody/tr/td[2]/a/span</value>
      <webElementGuid>4d5f1e55-444d-4877-a714-de22ad2c20a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[3]/following::span[3]</value>
      <webElementGuid>de93da09-e124-4a53-8722-09dc21112b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imports'])[1]/following::span[3]</value>
      <webElementGuid>ea858b8d-1562-439f-bc69-c43efbbd26bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test client PK'])[1]/preceding::span[2]</value>
      <webElementGuid>3d9ad0a5-ed39-45e0-83d0-4d3108115732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Client'])[1]/preceding::span[4]</value>
      <webElementGuid>5c83236e-e484-457a-b57a-f363b13d809c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/span</value>
      <webElementGuid>636673a8-4170-4647-b6da-c76fccfefa3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l1_0-5_0-ClientName' and (text() = 'TesteDavid' or . = 'TesteDavid')]</value>
      <webElementGuid>a7f8f887-4ab6-464e-97fc-f47ef046332b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
