<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Employee_Destionation</name>
   <tag></tag>
   <elementGuidId>b98d32a1-44f0-43c8-97c2-ff5b42410bce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'Content3') and (text() = 'Germany' or . = 'Germany')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Content3</value>
      <webElementGuid>7c222905-d23a-4860-b24d-87d848612ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Germany</value>
      <webElementGuid>b1a692a1-ba5f-49cd-b0a7-0561319e9b93</webElementGuid>
   </webElementProperties>
</WebElementEntity>
