<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag your JPEG, PNG file hereor  select_dad688</name>
   <tag></tag>
   <elementGuidId>e7f885ba-482d-45e9-8fde-39fa354c15c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.border-dashed.padding-l.align-items-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Upload_Info']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06788894-2644-40fc-915a-1954771997ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-dashed padding-l align-items-center</value>
      <webElementGuid>c70e1eee-93f1-46df-9412-8b56b693012f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag your JPEG, PNG file hereor  select files to uploadUp to 3MB</value>
      <webElementGuid>387c2e0e-30f2-4d9a-aa6c-b721ac17886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Upload_Info&quot;)/div[@class=&quot;border-dashed padding-l align-items-center&quot;]</value>
      <webElementGuid>d05346dc-1bc9-4310-a149-57d5ed92070f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Upload_Info']/div</value>
      <webElementGuid>f9877ed4-f8af-476c-82e6-1e49355cf045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client logo'])[1]/following::div[6]</value>
      <webElementGuid>0e733088-4bf6-4084-9e80-38992c56415e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Client'])[2]/following::div[10]</value>
      <webElementGuid>601b5f04-9346-4187-9702-f5e470e7404c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>d0dd7d0b-1243-453e-bc0b-18cb7ba47d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drag your JPEG, PNG file hereor  select files to uploadUp to 3MB' or . = 'Drag your JPEG, PNG file hereor  select files to uploadUp to 3MB')]</value>
      <webElementGuid>6337af7b-a11d-45b6-aabe-47e9ce40d618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
