<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Search</name>
   <tag></tag>
   <elementGuidId>9144b314-2c58-47f6-800b-9b3b0c8340f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'search' and @placeholder = 'Search' and contains(@id, 'Input_Dummy_Search')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b307d9d4-a99e-445e-8d5b-f6cda789ff15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>c343b763-1d20-4fd3-b8d0-9abc6f8d671a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Dummy_Search</value>
      <webElementGuid>2b8d122e-ba1f-49b9-908d-ee3bca3d6d1a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
