<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client name_Input_ClientName</name>
   <tag></tag>
   <elementGuidId>67cdff76-63ec-43aa-ad80-73fe1ffd50de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_ClientName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = 'TesteDavid' and @id = 'Input_ClientName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Input_ClientName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>533576de-0fee-4a9e-bab4-7c7a07e103a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>0ae3e523-cceb-4787-8bc9-c7b2cedf10ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a2b7d43-a5c6-4e26-a39b-258518f2e73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6462048b-74b7-4bda-9c0e-5deda4a25ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Input_ClientName_DescribedBy</value>
      <webElementGuid>f6776210-6e16-4a9f-9d73-91847442a051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TesteDavid</value>
      <webElementGuid>f4cf3016-86cc-49f5-91c0-b58b9062d051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_ClientName</value>
      <webElementGuid>afeb9c0b-c39f-4258-ac04-3b45c3411f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_ClientName&quot;)</value>
      <webElementGuid>464bbd57-5b9e-41c6-ab2a-592ebab4c931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TesteDavid</value>
      <webElementGuid>ac8c9097-688a-4a1c-8a02-04332395bbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_ClientName</value>
      <webElementGuid>85bc59bb-3017-4e7c-b809-884e8d85550a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_ClientName']</value>
      <webElementGuid>916198dd-bc79-4037-8003-0fbd2faf4086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b9-Input']/span/input</value>
      <webElementGuid>4b478736-4cfd-4eda-bba2-d5dba732fd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>db610f7d-8805-4cdd-b5a8-76f96bef6529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_ClientName']</value>
      <webElementGuid>d0c60a5d-cb33-46f1-82a7-aa20c4971884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
