<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_Input_LastName</name>
   <tag></tag>
   <elementGuidId>ee8fe00e-b65a-43fd-9e04-1f873e760a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_LastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_LastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2eda0274-53e8-4c85-954a-adfab0a696fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>f6a37986-6d43-43a7-9951-548b9fc060c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec2b9cc5-f9dc-4817-88dc-6162f7d472fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29508fd4-009c-49eb-89e1-8bdda14c99e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Input_LastName_DescribedBy</value>
      <webElementGuid>8774e4f6-f29a-4f29-b7b3-0677d3eae012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NaoMexer</value>
      <webElementGuid>ba9a32fc-e305-4f1b-bc4c-6b87b2497b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_LastName</value>
      <webElementGuid>67b15d0a-f86b-4ed7-af6b-4da3ae9d3a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_LastName&quot;)</value>
      <webElementGuid>8eae1d57-0fca-41ab-b099-24a30d426238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_LastName']</value>
      <webElementGuid>efc812a0-173a-4fb6-95e4-2e2cf4bf2907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b10-Input']/span/input</value>
      <webElementGuid>f0a71313-faf3-40e3-89c7-e8aaa0bfa8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/span/input</value>
      <webElementGuid>1a136f6d-d277-4a5f-8c56-f75a40f191ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_LastName']</value>
      <webElementGuid>9a283b84-9192-4889-ae94-5741f2a4e869</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
