<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_Input_ClientEmail</name>
   <tag></tag>
   <elementGuidId>08d41dec-7176-46fa-b0d8-5d5279159732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_ClientEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_ClientEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01f05440-be11-449d-91cb-e56a7377b7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>1d5bb690-ca62-4cc2-b64a-87c49ef38a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ca432add-8a52-4598-9307-98f1f3225ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a33158bd-8c21-4ff4-b31b-ce9bbfd19135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Input_ClientEmail_DescribedBy</value>
      <webElementGuid>e1a0250e-7713-43a9-a25d-64fb32748eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>testenaomexer@gmail.com</value>
      <webElementGuid>4c7069c8-3f63-4348-b19b-d9783a15efc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_ClientEmail</value>
      <webElementGuid>3ce1f218-8914-47a6-8dce-ad95584a06b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_ClientEmail&quot;)</value>
      <webElementGuid>a127c356-00b9-48db-9732-1287aa279505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_ClientEmail']</value>
      <webElementGuid>0e51e534-3b2d-48e2-b07b-a375efc74680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b11-Input']/span/input</value>
      <webElementGuid>8fe3f1d6-d3fd-430b-8813-eec18f6e7af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>d97813c7-7fb9-4268-92ab-0316c173c3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'Input_ClientEmail']</value>
      <webElementGuid>701b8df9-11ec-4bb3-9fe5-b094d3c9ba2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
