<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_Input_ClientName2</name>
   <tag></tag>
   <elementGuidId>8809dd1b-847e-41bd-bc56-7759446e64c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_ClientName2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_ClientName2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bbc42b2-f71b-4e5d-b2c3-d86908b660e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>6ccea88b-565b-4239-8898-a5c1d9c5e9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4676e8be-6317-4550-8e29-faa7a62ac006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>679a3911-8b5a-4cfa-a929-257ce99daef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Input_ClientName2_DescribedBy</value>
      <webElementGuid>747ebaef-a4cf-425f-a14b-7b7fdf5d93cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>testenaomexer</value>
      <webElementGuid>e9e29109-fab1-4d79-8e97-4201998a2eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_ClientName2</value>
      <webElementGuid>e663aef6-739a-494c-9ae4-7d7f28dff72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_ClientName2&quot;)</value>
      <webElementGuid>2b3a343b-a590-483f-8a9b-01b72a7fc5d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_ClientName2']</value>
      <webElementGuid>2bdb0024-0eba-40a2-a508-f1483646d6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-Input']/span/input</value>
      <webElementGuid>e4bf8c1e-5efb-4398-93cb-37648a8142b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>6efd5433-b4d0-472d-bb2e-ab01fe7822b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_ClientName2']</value>
      <webElementGuid>1b6bb100-7164-4ae6-b7b2-c5b33041a3f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
