<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Users</name>
   <tag></tag>
   <elementGuidId>c61214e7-ed23-40f7-a21a-d84dba1acf4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b4-b1-l2-14_1-NavigationItemName_Expr']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'NavigationItemName_Expr') and (text() = 'Users' or . = 'Users')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4-b1-l2-14_1-NavigationItemName_Expr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NavigationItemName_Expr</value>
      <webElementGuid>7993a843-9970-47f0-b68c-59266b282e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>23e5d2a2-1570-4de4-b1b5-61bb2fd17f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b4-b1-l2-14_1-NavigationItemName_Expr']</value>
      <webElementGuid>59bdcaf8-19c5-4cde-9205-65dc5eecc82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b4-b1-l2-14_1-NavigationItemName_link']/span</value>
      <webElementGuid>bc6b158f-43ef-4c3c-9a68-671711c91c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[2]/following::span[1]</value>
      <webElementGuid>2029441b-4f16-4420-b6ae-2becf7a91835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global advantage'])[1]/following::span[2]</value>
      <webElementGuid>69eb186a-4d9f-4963-9ccc-3d9491e566f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange rates'])[1]/preceding::span[1]</value>
      <webElementGuid>223da766-3531-4623-8bfc-c41cbb514825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OANDA'])[1]/preceding::span[2]</value>
      <webElementGuid>32a23ee2-8daf-4455-a267-71c60dd0e543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users']/parent::*</value>
      <webElementGuid>27e8e7a3-7a3e-4fe7-af3e-d1d9f19c7271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>61f17ee5-8231-468b-81ad-3b14cc352fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b4-b1-l2-14_1-NavigationItemName_Expr' and (text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>309247bc-75f1-4eef-a1a9-5f218725c2c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
