<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Last nameEmail</name>
   <tag></tag>
   <elementGuidId>18cca961-1420-4a7a-9872-cacc4f4ce9bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b6-b1-Column2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b6-b1-Column2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4940f423-265e-4759-a9c1-11df4fcab116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item</value>
      <webElementGuid>a184f281-27ac-4965-97da-a6930c7d0876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b6-b1-Column2</value>
      <webElementGuid>df68191d-0da1-4c46-a876-be106e703c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last nameEmail</value>
      <webElementGuid>7a1b8694-a684-48a6-bbf1-22fd6f066308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b6-b1-Column2&quot;)</value>
      <webElementGuid>706878e1-e953-4208-ac8a-47a66c42de25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b6-b1-Column2']</value>
      <webElementGuid>3a5e9115-a309-4a3f-bcfd-de862c5d2037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b6-$b1']/div/div[2]</value>
      <webElementGuid>237d75f1-8aaf-43b9-983b-e2e3274295d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[2]/following::div[8]</value>
      <webElementGuid>ca4b7afe-7a0e-4891-ba29-a34ac2e679c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GCM User'])[1]/following::div[9]</value>
      <webElementGuid>d5d941b8-75a3-4074-ad5d-c4b8a3bd87ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]</value>
      <webElementGuid>1101f1ab-939f-4c1b-805a-974bef5d368e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b6-b1-Column2' and (text() = 'Last nameEmail' or . = 'Last nameEmail')]</value>
      <webElementGuid>23b3215d-ad7e-48c9-9173-bc83b4fb7add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
