<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_File_GCM-icons icon-expand_less text-neut_87bcbf_1</name>
   <tag></tag>
   <elementGuidId>938067de-3597-4c2f-a47d-9dad92e8d199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l1_0-51_1-b13-ArrowDetail']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.GCM-icons.icon-expand_less.text-neutral-6.fa-24.fa.fa-flag.fa-1x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5a598b04-5e7d-4eb4-b937-d7b019f5c09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-expand_less text-neutral-6 fa-24  fa fa-flag fa-1x</value>
      <webElementGuid>b59f9784-1316-4db7-9285-5f41abf97e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-51_1-b13-ArrowDetail&quot;)/i[@class=&quot;GCM-icons icon-expand_less text-neutral-6 fa-24  fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>4189f0d9-b522-42e9-b69a-d6b10777e782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l1_0-51_1-b13-ArrowDetail']/i</value>
      <webElementGuid>4d8ba1b6-90c2-4918-9395-61957c789fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[9]/div/a/span/div/i</value>
      <webElementGuid>111261a8-7ba1-4cce-9a24-1b60bd31dadc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
