<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ImportsFile_Icon</name>
   <tag></tag>
   <elementGuidId>d20b18d6-bbce-4606-99fb-71e7f7d3a33c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'add_icon')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b8-b9-$b2']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.GCM-icons.icon-add-converted.text-neutral-6.fa-24.fa.fa-flag.fa-1x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_icon</value>
      <webElementGuid>46806f60-d033-4af9-9c9c-d473dc847248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-b9-$b2']/i</value>
      <webElementGuid>ed0d9492-4776-49ec-987b-cd32e2636adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div/i</value>
      <webElementGuid>8c2b651f-12ff-493a-afc2-a5c5c65d209a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
