<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Processes_Tab</name>
   <tag></tag>
   <elementGuidId>b002b323-8b00-4e81-aedb-557ede13e5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'ListItem1') and (text() = 'Processes' or . = 'Processes')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b3-b1-l1-45_1-TopNavItem']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ListItem1</value>
      <webElementGuid>1408a16b-24c2-49af-aab8-05c2d9f1a580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processes</value>
      <webElementGuid>73d2e5a2-33b4-4e7d-b7a1-86b049436d11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b3-b1-l1-45_1-TopNavItem']/span</value>
      <webElementGuid>fc12def2-f7fd-4694-86b1-0ce53bd5d6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/following::span[1]</value>
      <webElementGuid>3549ce2c-037e-4b2f-9b3f-a93b0a362e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevClient'])[1]/following::span[3]</value>
      <webElementGuid>9d213b87-3fb9-4b6b-bc90-8d4568bc2456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/preceding::span[1]</value>
      <webElementGuid>7e80fcde-7eed-425b-823f-7d3d6490a22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::span[3]</value>
      <webElementGuid>7be88e0e-5b93-405e-80a3-b966713f309c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Processes']/parent::*</value>
      <webElementGuid>ded4d5f1-802f-42b7-90d2-c3b55a0e0a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>3d398e29-2871-4c14-8755-34629d6a2a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Processes' or . = 'Processes')]</value>
      <webElementGuid>e4d07d83-d8d0-4687-83ea-15dfde0c36f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b3-b1-l1-52_1-TopNavItem']/span</value>
      <webElementGuid>8e7dd2c5-fe9a-4581-92fa-340d3b9cc764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
