<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectFilesToUpload_Screen</name>
   <tag></tag>
   <elementGuidId>e50b8eb6-c542-45f9-89d6-0320fc3bb144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'file']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='$b26']/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn.btn-upload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>905cb192-0aa0-45f7-b94b-a7509a345898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b26']/div/div/div/span[2]</value>
      <webElementGuid>746934a6-52b1-4588-a380-8118c998e6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::span[1]</value>
      <webElementGuid>81c146b1-b033-45a9-ae07-f47493ca3f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag your DOC, PDF, XLS or XML file here'])[1]/following::span[2]</value>
      <webElementGuid>7d0a2bda-91c5-4f5e-aa0b-cd6b8eb1e348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sample file'])[1]/preceding::span[2]</value>
      <webElementGuid>a9b0ee98-c38b-42ec-9a3a-c5eedffbbb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use our sample document in order to make this process easier'])[1]/preceding::span[2]</value>
      <webElementGuid>9b81a56c-36f0-4d4a-b5ad-727775764a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='select files to upload']/parent::*</value>
      <webElementGuid>f59423c3-78f0-45dd-ae68-91f13a388126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span[2]</value>
      <webElementGuid>905311ac-6e99-4d71-abe7-cdb478de9db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' select files to upload' or . = ' select files to upload')]</value>
      <webElementGuid>1b4b8a5d-5ca7-4b9f-84a7-aad20a84e640</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
