<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SMS_Insert_Code</name>
   <tag></tag>
   <elementGuidId>d156b6dd-a3b3-4720-8137-6923dc49a888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idTxtBx_SAOTCC_OTC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f95116a-5eb4-4a79-8f41-2f893c87db6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC</value>
      <webElementGuid>7b02ccfb-4a6f-4ccb-b533-e81d5189a3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc</value>
      <webElementGuid>c5dc044f-a497-4157-b7c3-3609e448f4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f5d2bbd3-738f-4afc-93c3-76c33c034565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>5f01eb3b-8ca2-4c9c-928b-dc818dfbac39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a427faf4-40db-4eba-a5c1-30b1b97ce6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd284a0e-eb9d-4011-b895-143c0c6883fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                  attr: {
                      'maxlength': otcLength,
                      'aria-labelledby': 'idDiv_SAOTCC_Title',
                      'aria-describedby': 'idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC' },
                  css: { 'has-error': error },
                  textInput: otcInputTextbox.value,
                  ariaLabel: str['CT_SAOTCC_STR_OTC_TBHint'],
                  hasFocusEx: otcInputTextbox.focused,
                  placeholder: $placeholderText</value>
      <webElementGuid>bb15dc1e-cf40-499e-89cf-5c18cd15d8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a7d1e015-e20f-46db-a0d7-7c1108431af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idDiv_SAOTCC_Title</value>
      <webElementGuid>17529dc0-29ed-4236-8547-519cb5396acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC</value>
      <webElementGuid>d864e788-53e2-46c6-9f7a-51f8cb1b8158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>d4dbca64-d54d-4515-baaf-99cf2912d9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>569a3a6e-02d7-441d-b362-17842692357b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTxtBx_SAOTCC_OTC&quot;)</value>
      <webElementGuid>0740076e-8e5e-4177-aaa8-e361c7cd2921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ac09881-e986-44b2-947f-31d6539537d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC</value>
      <webElementGuid>26fa763f-7864-484e-9e06-51d90aff65b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc</value>
      <webElementGuid>e5b031e4-202c-4b98-b883-3c3ccebdbef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>03257ebf-a55a-45a1-a3af-afe165a0008f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1ea9ac4a-4459-48b4-ae23-0b2a746da966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94b4fd03-cbc1-4bd0-9e73-558abdcc6ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>195aa017-10cf-4143-a0b9-a13f9b2dce46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                  attr: {
                      'maxlength': otcLength,
                      'aria-labelledby': 'idDiv_SAOTCC_Title',
                      'aria-describedby': 'idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC' },
                  css: { 'has-error': error },
                  textInput: otcInputTextbox.value,
                  ariaLabel: str['CT_SAOTCC_STR_OTC_TBHint'],
                  hasFocusEx: otcInputTextbox.focused,
                  placeholder: $placeholderText</value>
      <webElementGuid>74e1afcd-8d86-4963-a319-634a8562afd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>1c8bef28-7070-48f3-8989-ada47ae31f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idDiv_SAOTCC_Title</value>
      <webElementGuid>b95c118d-c2b0-428f-af6f-2c939052a6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC</value>
      <webElementGuid>b09b396f-a870-4cb7-b4d5-a6648ee8a984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>753bcf3e-fb86-4ddf-892c-07008f5e4428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>248297ab-a58a-4dfa-9ae9-d8492b591bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTxtBx_SAOTCC_OTC&quot;)</value>
      <webElementGuid>ba0a55cb-9d3f-4a0b-a581-8e4f606c53e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4f2f168-fec4-4c8f-a9dc-090572ac5c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC</value>
      <webElementGuid>127c35be-157e-4a6e-adc3-a5ed3cd9bc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc</value>
      <webElementGuid>458aa921-97a9-42c3-9f13-c8b3a8e0d0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>61d241de-9db4-4dfb-9dbd-c3204cf8332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>b7e06372-357e-4f6a-a43c-8329b37a4b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1dc8e5a2-ae7f-4042-b6bd-05482cc5bb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40328c38-d4a0-4b54-a053-a8c2ddb97eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                  attr: {
                      'maxlength': otcLength,
                      'aria-labelledby': 'idDiv_SAOTCC_Title',
                      'aria-describedby': 'idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC' },
                  css: { 'has-error': error },
                  textInput: otcInputTextbox.value,
                  ariaLabel: str['CT_SAOTCC_STR_OTC_TBHint'],
                  hasFocusEx: otcInputTextbox.focused,
                  placeholder: $placeholderText</value>
      <webElementGuid>c0daf549-b778-4635-ba20-a3b74b75433a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>901de1e2-5f1d-4075-94e8-981a9d5912a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idDiv_SAOTCC_Title</value>
      <webElementGuid>9b2bb693-d48d-441f-9ed8-e89168619e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC</value>
      <webElementGuid>7395be91-4a8b-4235-a3ab-fbfa8b267697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>0c30ef82-03dc-40e2-ba95-22f87e36bb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>d78f36e2-e790-496e-a3ba-92c43a22fb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTxtBx_SAOTCC_OTC&quot;)</value>
      <webElementGuid>d0be17b2-11a8-4d97-8dfb-8563f8aec8ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      <webElementGuid>3caab1b4-49b8-4538-ab7c-9e98d7b34cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDiv_SAOTCC_OTC']/div/input</value>
      <webElementGuid>9f38c315-1029-43c7-ba08-485a591e58f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>9bb31eda-36db-4009-b838-ebed81ab2379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idTxtBx_SAOTCC_OTC' and @name = 'otc' and @type = 'tel' and @placeholder = 'Código']</value>
      <webElementGuid>d4bc211f-fa3c-4211-adea-eb20c59d7260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
