<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Employee Details</name>
   <tag></tag>
   <elementGuidId>153fc717-5209-449b-929d-5d2a003e8c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b8-b9-l2-39_2-l2-42_0-ImportItem3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b8-b9-l2-39_2-l2-42_0-ImportItem3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Modal-Menu-ListItem' and (text() = 'Risk Assessment' or . = 'Risk Assessment')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Modal-Menu-ListItem</value>
      <webElementGuid>d0a2b74b-0fe2-4234-b790-c0b597ae9ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Risk Assessment</value>
      <webElementGuid>a286da78-732c-473f-b371-edb9b30627ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b8-b9-l2-39_2-l2-42_0-ImportItem3']</value>
      <webElementGuid>9b94dc70-795f-41e3-aa17-a62561bb3c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div[2]/div/div/div/span</value>
      <webElementGuid>7789cb5f-8171-4753-b3a0-92f72c12cd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Import'])[1]/following::span[1]</value>
      <webElementGuid>1275561c-a1ff-477e-a3c3-ea30e3b63bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feature to be developed'])[2]/following::span[2]</value>
      <webElementGuid>5aeac24c-a33b-4b0c-8d77-074681ec9cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Contracts'])[1]/preceding::span[1]</value>
      <webElementGuid>a8f1baf5-39d0-498b-97db-5e72ed8c14fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Travels'])[1]/preceding::span[2]</value>
      <webElementGuid>e3fc0dc8-0d74-48ce-aff9-aa77553000ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employee Details']/parent::*</value>
      <webElementGuid>0dfb0d0a-41a9-42a4-883f-97d0db38da22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>cc2e6d43-ff4a-4234-8198-93f792e4626a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b8-b9-l2-39_2-l2-42_0-ImportItem3' and (text() = 'Employee Details' or . = 'Employee Details')]</value>
      <webElementGuid>d669378b-1aba-4153-a1f0-7f778f7e2b1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
