<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DevClient</name>
   <tag></tag>
   <elementGuidId>f83ebcc6-de78-4c2e-8399-6fee2b7bcfa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='l1_0-51_0-ClientName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l1_0-21_1-ClientName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, '0-ClientName') and (text() = 'DevClient' or . = 'DevClient')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0-ClientName</value>
      <webElementGuid>0be9f5cd-81f0-4e70-a709-17ef49c8392e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DevClient</value>
      <webElementGuid>3b019402-5132-418d-adb0-9358d886d677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l1_0-21_1-ClientName']</value>
      <webElementGuid>a64f4b0f-1873-4d81-8081-def87f57f0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ResultsTable']/tbody/tr[2]/td[2]/a/span</value>
      <webElementGuid>1cd3bdb6-2500-4745-a6e4-b49e0c1196d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dev Review'])[1]/following::span[2]</value>
      <webElementGuid>809e3160-8e56-4d4b-86c4-aabaeac66970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients'])[3]/following::span[5]</value>
      <webElementGuid>f31ddd88-dff4-4a57-b520-0def75d9e3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevClient'])[2]/preceding::span[2]</value>
      <webElementGuid>29bcd579-e5ff-4211-9db3-457898ad7491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevClient'])[3]/preceding::span[4]</value>
      <webElementGuid>3735a122-be46-487a-b131-57b09f3eb7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a/span</value>
      <webElementGuid>0b5d5e72-9062-4160-a5e7-5d10d550dc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l1_0-21_1-ClientName' and (text() = 'DevClient' or . = 'DevClient')]</value>
      <webElementGuid>3cb3cff7-e648-4eff-ab91-af4d2ecb77eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l1_0-22_1-ClientName']</value>
      <webElementGuid>1ec16983-d4d6-4128-a9b7-5741a1ca7099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DevClient']/parent::*</value>
      <webElementGuid>49d709e3-c6d8-4873-b396-936ed1622579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l1_0-22_1-ClientName' and (text() = 'DevClient' or . = 'DevClient')]</value>
      <webElementGuid>35ddae55-d58a-421f-a160-fa73d4c81987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='l1_0-21_3-ClientName']</value>
      <webElementGuid>6fcb0579-ee67-474b-a756-f5ebd9a64d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ResultsTable']/tbody/tr[4]/td[2]/a/span</value>
      <webElementGuid>a44ec14e-55eb-4b22-919b-6a1d5b87bdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Debug'])[1]/following::span[2]</value>
      <webElementGuid>bf9cb1ab-2e25-4cb8-b289-31bcfe82bd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dev Review'])[1]/following::span[4]</value>
      <webElementGuid>86f53a70-d540-4f12-871d-f1d63e54e003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a/span</value>
      <webElementGuid>7dc32676-556a-458d-a977-ae1e85fe010f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'l1_0-21_3-ClientName' and (text() = 'DevClient' or . = 'DevClient')]</value>
      <webElementGuid>183edf71-cdb9-4742-bc63-0f5b64bac38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
