<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProcessesTab</name>
   <tag></tag>
   <elementGuidId>f6d83329-3cf0-4134-9be7-dff6e47b5d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b3-b1-l1-45_1-TopNavItem']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'ListItem1') and (text() = 'Processes' or . = 'Processes')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ListItem1</value>
      <webElementGuid>642a1f5d-ce5c-4db2-aeb5-d779410f3500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processes</value>
      <webElementGuid>117e1600-1e3d-44d0-ba84-c33ae03c7d30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b3-b1-l1-45_1-TopNavItem']/span</value>
      <webElementGuid>b47b1c90-3f5d-4c72-a7c5-173320e51fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[1]/following::span[1]</value>
      <webElementGuid>83122392-106c-4887-8f7e-739e9532ab30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DevClient'])[1]/following::span[3]</value>
      <webElementGuid>69fe158c-55bb-43c4-967d-59e0d7bc01ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/preceding::span[1]</value>
      <webElementGuid>29a15167-ec43-49fc-ace3-5d8c85f1e978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::span[3]</value>
      <webElementGuid>bb0df11c-04b5-46b4-be09-3ceb326d8421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Processes']/parent::*</value>
      <webElementGuid>d7a6275d-3364-45e3-8288-b39431434f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>09ab2641-9439-4147-8e7d-75843416e64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Processes' or . = 'Processes')]</value>
      <webElementGuid>0ea09f6e-b696-4653-a96f-087ff8c4eed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
