<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Updated_Client_ExchangeRate</name>
   <tag></tag>
   <elementGuidId>4db88458-cf39-460e-9c1d-fe9eeae332e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'ListItem8') and (text() = 'OANDA' or . = 'OANDA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ListItem8</value>
      <webElementGuid>dede1366-4c5e-4d90-ba7c-d584de9f96a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OANDA</value>
      <webElementGuid>a4a2899c-db63-45ad-ac2e-6c687e2d6597</webElementGuid>
   </webElementProperties>
</WebElementEntity>
