<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_User_Role</name>
   <tag></tag>
   <elementGuidId>2af62a8b-3b11-4144-a59e-05a23216110f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'ListItem3') and (text() = 'Admin' or . = 'Admin')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ListItem3</value>
      <webElementGuid>10dfbf3e-f6a0-4612-a5dc-fd95dd93a2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>665a546f-70b5-4d03-84ea-9cda95252bf0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
