<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_User_FirstName</name>
   <tag></tag>
   <elementGuidId>18b3b317-8f93-449d-aace-a032a3808da2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = 'Teste' and contains(@id, 'Input_Firstname')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Teste</value>
      <webElementGuid>9ad790d8-4da9-4fc7-a65f-7b9579265a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Firstname</value>
      <webElementGuid>80bb6f56-cddc-45e5-ad6b-0fbc5afb951f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
