<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OANDA</name>
   <tag></tag>
   <elementGuidId>e009d987-455e-41ea-b576-bfa57b1e9769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l1-41_0-ListItem8']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ListItem8' and (text() = 'OANDA' or . = 'OANDA')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l1-41_0-ListItem8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ListItem8</value>
      <webElementGuid>2b745881-cd89-48ee-abb2-872480026af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OANDA</value>
      <webElementGuid>fdb0b88e-4bac-4738-bf9d-288e1621678e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='l1-41_0-ListItem8']</value>
      <webElementGuid>27d79713-a1e2-494d-ba60-fd7f0b1bef79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='List_ExRates']/div</value>
      <webElementGuid>70a05314-4a86-4aea-a722-c3751bf2eee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USt-FX Rate'])[2]/following::div[6]</value>
      <webElementGuid>fd0239fd-a359-48cd-a6ed-d094f6680593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[8]</value>
      <webElementGuid>d7da6606-8476-46bc-9678-c09330c4e612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USt-FX Rate'])[3]/preceding::div[1]</value>
      <webElementGuid>21a979ea-f154-4abf-9747-deba51cb697e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div</value>
      <webElementGuid>d06aadaf-d90a-4847-b9c5-a924a65b09ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'l1-41_0-ListItem8' and (text() = 'OANDA' or . = 'OANDA')]</value>
      <webElementGuid>92b4c8f6-b5ce-4d75-a7ce-0b5600abe2ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
