<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client name_Input_ClientName (1)</name>
   <tag></tag>
   <elementGuidId>066d0908-8bd8-42df-8bf8-9ca2bc6c0645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_ClientName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_ClientName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TesteDavid</value>
      <webElementGuid>ac8c9097-688a-4a1c-8a02-04332395bbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_ClientName</value>
      <webElementGuid>85bc59bb-3017-4e7c-b809-884e8d85550a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_ClientName']</value>
      <webElementGuid>93a31aa9-8444-49e3-a097-a58575684dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b9-Input']/span/input</value>
      <webElementGuid>8186a0e1-64db-4d3f-a2db-c98868bd6973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bb440cad-5bb5-46c2-91fb-47732e77f90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Input_ClientName']</value>
      <webElementGuid>b393594d-8aa7-4e85-810b-5de1ef8fbfa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
