<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Envimos-lhe uma mensagem para o telef_613582 (1)</name>
   <tag></tag>
   <elementGuidId>4276b839-1111-4157-afbb-477ebee778f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idTxtBx_SAOTCC_OTC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5115f5b8-bba8-4936-9826-9a261e815a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idTxtBx_SAOTCC_OTC</value>
      <webElementGuid>caa0e2fb-1c0c-4e2f-80f9-2566389b8240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otc</value>
      <webElementGuid>f638e029-fe7e-4a51-9a36-e60eabcc6e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0726d6d9-2db1-4e7f-a8bb-f1298275f1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>652e6067-03fe-49cb-88df-a4686fa39586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aaab4fe8-6afa-4489-8404-25f2d53fb7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42f1f839-d992-47bd-8a5c-f4213fd7aede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                  attr: {
                      'maxlength': otcLength,
                      'aria-labelledby': 'idDiv_SAOTCC_Title',
                      'aria-describedby': 'idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC' },
                  css: { 'has-error': error },
                  textInput: otcInputTextbox.value,
                  ariaLabel: str['CT_SAOTCC_STR_OTC_TBHint'],
                  hasFocusEx: otcInputTextbox.focused,
                  placeholder: $placeholderText</value>
      <webElementGuid>3a8210a0-9488-428e-90fe-788ccf01ec74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ebc21c14-daa6-49a3-b8e4-29626bbb8d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idDiv_SAOTCC_Title</value>
      <webElementGuid>80d690ce-7f15-4cbd-8984-3d1eef53e345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idDiv_SAOTCS_Title idDiv_SAOTCC_Description idSpan_SAOTCC_Error_OTC</value>
      <webElementGuid>8cc2e9c4-6fbc-4293-8d80-ce5bd48a5949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>180b5f70-2af6-4c72-bde4-d5b4bddf93c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Código</value>
      <webElementGuid>45d3afaa-7b1a-4e79-b7d7-804c9f5c8be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idTxtBx_SAOTCC_OTC&quot;)</value>
      <webElementGuid>1f346a58-39b8-4fa8-9bfd-076643e319d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idTxtBx_SAOTCC_OTC']</value>
      <webElementGuid>45cdf757-42a9-42a8-8435-3bbe580eb915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idDiv_SAOTCC_OTC']/div/input</value>
      <webElementGuid>57183ee9-e2de-460b-9aa9-5e418355c26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>7bef9060-e918-4556-bc49-b9d6fea07226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idTxtBx_SAOTCC_OTC' and @name = 'otc' and @type = 'tel' and @placeholder = 'Código']</value>
      <webElementGuid>a09c5fb3-eb00-4713-83b9-cef2d803749c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
