<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_ClientName</name>
   <tag></tag>
   <elementGuidId>47ba51d1-97d0-4300-a9bd-20ae960166f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and contains(@id, 'Input_ClientName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47335afc-b1ce-40d3-b8c1-f310d529d915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_ClientName</value>
      <webElementGuid>656861a3-eb11-4f47-9918-22352aab7ef5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
