<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Updated_ClientImage</name>
   <tag></tag>
   <elementGuidId>10bf965d-43c9-4924-ad20-ff24aad9820d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'Preview') and @src = 'https://gcm.ges-de-dev.deloitte.pt/ec29f004-9e41-422b-a7fe-6a3b7955c524']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>047d64b6-d079-4fa6-8628-6ac6527d7479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://gcm.ges-de-dev.deloitte.pt/ec29f004-9e41-422b-a7fe-6a3b7955c524</value>
      <webElementGuid>06fa948b-c08d-4548-a3fe-4e1384c14012</webElementGuid>
   </webElementProperties>
</WebElementEntity>
