<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_FileUpload</name>
   <tag></tag>
   <elementGuidId>6f93bd2a-2391-4c1d-9dd5-ac8a9c766a3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b30-Button > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b30-Button']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e29b44e4-06d7-492b-8996-a6ec94119457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>f664e87c-345f-4cb6-b8dd-d4ae9a8ac09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b30-Button&quot;)/span[1]</value>
      <webElementGuid>9a14f4b6-f797-4e77-95af-6e6347ec6521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='b30-Button']/span</value>
      <webElementGuid>30a6932e-a310-4973-b2b4-e20609545b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Sample File'])[1]/following::span[1]</value>
      <webElementGuid>555ba577-b1bb-4a37-883f-306c8b3b4ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use our sample document in order to make this process easier'])[1]/following::span[2]</value>
      <webElementGuid>1de70eb8-b2ea-4f50-951a-1762db3efe75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>4f8b6b2f-066f-4ca1-aec4-be7e2dde3cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>47d87901-13e5-4fea-b4a8-8874572524a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>5666ca41-36a9-46bf-a0d8-9b58ff9479cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
