<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CalendarData_February</name>
   <tag></tag>
   <elementGuidId>7b31501b-93c9-4794-a7c4-239f8917673f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b27-l1-96_1-b3-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b27-l1-96_1-b3-month']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'month') and (text() = 'February' or . = 'February')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>4c474ecc-ad77-43bd-a998-94439ecf64a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>February</value>
      <webElementGuid>7e811179-51eb-4b45-84bd-7f0a5293888c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b27-l1-96_1-b3-month']</value>
      <webElementGuid>ffb8d417-5c42-4d6b-8cac-fd7032f813f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b27-l1-96_1-$b3']/div/div/span</value>
      <webElementGuid>8f63d922-6fc1-4229-9520-08c04a52de8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::span[32]</value>
      <webElementGuid>a3e61860-5a5d-48f7-9c97-5c7d1a7ea9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::span[32]</value>
      <webElementGuid>32dc4385-532e-40bc-938c-6a32600ebe20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(7 workdays)'])[2]/preceding::span[1]</value>
      <webElementGuid>db5ff739-35ce-4030-b8e9-0a6bd9dddc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[2]/preceding::span[2]</value>
      <webElementGuid>a763e66c-5c9a-4a97-93d7-cf4b53915087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='February']/parent::*</value>
      <webElementGuid>3f899925-5e2f-4e93-8456-91732745af72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/span</value>
      <webElementGuid>1ae2292b-98b1-40f3-b879-14b521a02a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b27-l1-96_1-b3-month' and (text() = 'February' or . = 'February')]</value>
      <webElementGuid>7dff7838-2bc2-4620-8dc0-8c39457c1a1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
