<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clients_SearchBar</name>
   <tag></tag>
   <elementGuidId>f3666705-d5fa-4989-a2dc-6c181f79d090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Input_Dummy_Search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_Dummy_Search']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Input_Dummy_Search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_Dummy_Search</value>
      <webElementGuid>667fd64e-dc23-4e7d-aabe-8a1b8a1422a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_Dummy_Search']</value>
      <webElementGuid>3bbd1540-9687-43f5-a75f-8a968dd65605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-Input']/span/input</value>
      <webElementGuid>05094164-62fa-4016-9f04-fb94eab59db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>90d3732b-2112-4049-a11d-ff13d6034076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search' and @id = 'Input_Dummy_Search']</value>
      <webElementGuid>54f0967d-4705-4ca0-a0e7-142d160c9551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
