<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SideBar_ImportsTab</name>
   <tag></tag>
   <elementGuidId>f92c968f-27a9-44e8-a59a-57c76a8d1979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-l2-30_1-NavigationItemName_Expr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-b1-l2-30_1-NavigationItemName_Expr']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'NavigationItemName_Expr') and (text() = 'Imports' or . = 'Imports')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NavigationItemName_Expr</value>
      <webElementGuid>ebe4c2fc-b7b4-441b-9df5-2f3f9a383050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imports</value>
      <webElementGuid>c81de3d6-754f-4c7c-9288-a6cc31adf53b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-b1-l2-30_1-NavigationItemName_Expr']</value>
      <webElementGuid>035b38c3-5c4c-4887-9c45-64cbb0b1864a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-b1-l2-30_1-NavigationItemName_link']/span</value>
      <webElementGuid>aa72df58-d339-4ca2-adf0-3073f7f68ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/following::span[1]</value>
      <webElementGuid>47519d37-6b99-485c-9294-7e7a8efbdc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/following::span[4]</value>
      <webElementGuid>7b75323d-6bd8-4d3a-ab7f-7267d3439cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/preceding::span[1]</value>
      <webElementGuid>963a952f-2df0-4e8b-9f90-f5e92a9f2a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[3]/preceding::span[2]</value>
      <webElementGuid>5c50c5f6-3336-4164-9fbf-be89af4568d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imports']/parent::*</value>
      <webElementGuid>67b0d34f-c75b-4d7c-88a8-4663fa6bbe3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>52af4b7d-cf2c-4b29-ab42-a374f5b04404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-b1-l2-30_1-NavigationItemName_Expr' and (text() = 'Imports' or . = 'Imports')]</value>
      <webElementGuid>6ca1e039-a39d-4745-8057-9d743563330c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-b1-l2-20_1-NavigationItemName_Expr']</value>
      <webElementGuid>4519e6cf-d41f-4189-9e1b-53d4fdd91e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-b1-l2-20_1-NavigationItemName_link']/span</value>
      <webElementGuid>d0d3b27f-4a27-4ad5-8f0c-ad5c29cac457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-b1-l2-20_1-NavigationItemName_Expr' and (text() = 'Imports' or . = 'Imports')]</value>
      <webElementGuid>caf70365-2d92-4a3d-829b-4557bfaaee14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
