<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SideBar_EmployeesTab</name>
   <tag></tag>
   <elementGuidId>2e12cd66-4f3b-40f4-b5ed-79cc7ac9b7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-l2-46_2-NavigationItemName_Expr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='b5-b1-l2-46_2-NavigationItemName_Expr']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'NavigationItemName_link') and (text() = 'Employees' or . = 'Employees')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NavigationItemName_link</value>
      <webElementGuid>963763e8-7caa-4d24-bcf0-75fae12424cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>020830c0-1402-4a9e-9281-3e2b0af40596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-b1-l2-46_2-NavigationItemName_Expr']</value>
      <webElementGuid>12f1faf9-73db-4731-b901-9c8511bfe391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-b1-l2-46_2-NavigationItemName_link']/span</value>
      <webElementGuid>8bfde686-23e0-43dd-8554-f7e64ccfe6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::span[1]</value>
      <webElementGuid>1e4137bd-3637-4dd3-98c4-1903740ce5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[2]</value>
      <webElementGuid>d0ecad90-4c81-4d0d-87fe-7a452aa577da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Contracts'])[1]/preceding::span[1]</value>
      <webElementGuid>b38b609e-d6a3-40a0-b70d-60cb40f2ba4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignments'])[1]/preceding::span[2]</value>
      <webElementGuid>1d9b3e0e-8c07-441f-8498-b2c79db0dd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employees']/parent::*</value>
      <webElementGuid>669aaa0e-d074-40aa-9f5d-ab73cba3124e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/div[3]/div/a/span</value>
      <webElementGuid>904c5849-7fcd-409c-99c9-4cc116944e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-b1-l2-46_2-NavigationItemName_Expr' and (text() = 'Employees' or . = 'Employees')]</value>
      <webElementGuid>9c9c9040-4f1a-44cf-9bcc-f11d1fa322a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
