<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Employees_Tab</name>
   <tag></tag>
   <elementGuidId>38022bca-113b-4678-b945-81a4fca79add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'NavigationItemName_link') and (text() = 'Employees' or . = 'Employees')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-l2-45_2-NavigationItemName_Expr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NavigationItemName_link</value>
      <webElementGuid>0573f634-7a72-4983-b67a-bb235e500f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>f713d674-0f4f-4b2b-9013-aa6f27beb76a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-b1-l2-45_2-NavigationItemName_Expr']</value>
      <webElementGuid>cbadea8f-99a1-4e33-8e42-08b0efc52bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-b1-l2-45_2-NavigationItemName_link']/span</value>
      <webElementGuid>b549c290-deb9-4cc6-bc30-928e04dfc9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::span[1]</value>
      <webElementGuid>15eb040e-de56-4619-a23a-df03207229b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[2]</value>
      <webElementGuid>abd8184b-01d5-41c2-9fc3-759fec3b42c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Contracts'])[1]/preceding::span[1]</value>
      <webElementGuid>6c2b1739-0870-40fd-9ba9-4dee000c3559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignments'])[1]/preceding::span[2]</value>
      <webElementGuid>9040eb2a-d9c9-4702-ac0b-d180cb33f2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employees']/parent::*</value>
      <webElementGuid>b21ece3b-c02b-4df4-900a-6fda1ea5503f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/div[3]/div/a/span</value>
      <webElementGuid>f10815a1-ce16-414b-ae2a-135bc0d21bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-b1-l2-45_2-NavigationItemName_Expr' and (text() = 'Employees' or . = 'Employees')]</value>
      <webElementGuid>dfae592a-4adc-4ece-8f19-35256f5941a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-b1-l2-46_2-NavigationItemName_Expr']</value>
      <webElementGuid>a26cef7b-b241-4453-89ae-b966c0349dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-b1-l2-46_2-NavigationItemName_link']/span</value>
      <webElementGuid>b1abc419-b242-4cfb-a841-ccf98cf48b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-b1-l2-46_2-NavigationItemName_Expr' and (text() = 'Employees' or . = 'Employees')]</value>
      <webElementGuid>ad497982-e2c4-4d4d-8ccc-4f269f9e4b39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
