<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Imports</name>
   <tag></tag>
   <elementGuidId>7dfdc2fc-f35c-4b83-be3c-1c5a0790a99f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b1-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3afe5dcd-c23b-4898-8dba-b1c77a45ca61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-top-title heading1 ph font-extra-bold </value>
      <webElementGuid>48827272-a0ba-4dd9-879f-e6430a2f1066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-Title</value>
      <webElementGuid>2cea2a1b-c2ab-48d0-bd44-45459f0e88a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imports</value>
      <webElementGuid>46f95fd1-b3bf-4cc1-9ee3-8cfb6dd3fe70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-Title&quot;)</value>
      <webElementGuid>7c6e5aa0-faab-44d3-a67b-ad6d82eb5b43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b1-Title']</value>
      <webElementGuid>2c36f37c-fbea-4a4b-919d-8f4b0a90c121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-MainContentWrapper']/div/div/div[2]/div</value>
      <webElementGuid>a89f3726-2b51-42e4-a68d-73d6bf63ff86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::div[4]</value>
      <webElementGuid>d44f6b76-67f2-4749-8a79-586448f86055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imports'])[2]/following::div[6]</value>
      <webElementGuid>12232c20-94e2-473b-9294-abe4d787016d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/preceding::div[16]</value>
      <webElementGuid>5eaf67b4-e96f-4b38-b67d-7548e6bbcb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compensation'])[1]/preceding::div[23]</value>
      <webElementGuid>101708c6-90b6-4307-a203-8c98522d5712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>410c643c-b14d-4f4f-89e5-25ee4fab5a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b1-Title' and (text() = 'Imports' or . = 'Imports')]</value>
      <webElementGuid>ed4f2acc-5cb7-451c-ba2f-e93a78430a1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
