<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Employee_GCM-icons icon-arrow_right text-_a32b7b</name>
   <tag></tag>
   <elementGuidId>67101cbd-5fd7-43b1-85af-ae75ff0b76c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b8-b9-l2-39_2-$b3']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'b8-b9-l2-46_2-$b3')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b8-b9-l2-46_2-$b3</value>
      <webElementGuid>117d6a64-a81b-4433-9ae9-26d685788b34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-b9-l2-39_2-$b3']/i</value>
      <webElementGuid>3ce4e9c7-513e-4f9e-89f2-688dd7076a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/i</value>
      <webElementGuid>6d2abdd9-e2a0-40b3-9d7c-5072fdbc1224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
