<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_File_GCM-icons icon-expand_less text-neut_87bcbf</name>
   <tag></tag>
   <elementGuidId>966f377d-61ac-4f34-87a6-3af861f81c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l1_0-51_0-b13-ArrowDetail']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.GCM-icons.icon-expand_less.text-neutral-6.fa-24.fa.fa-flag.fa-1x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a1ffcc8f-227d-477a-b8c9-c103b32e19c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-expand_less text-neutral-6 fa-24  fa fa-flag fa-1x</value>
      <webElementGuid>16bbc4c6-4a02-488a-a3dd-0834fe3000d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-51_0-b13-ArrowDetail&quot;)/i[@class=&quot;GCM-icons icon-expand_less text-neutral-6 fa-24  fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>9e02e6ad-04e7-485b-8512-d8f2b2837ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l1_0-51_0-b13-ArrowDetail']/i</value>
      <webElementGuid>a4af653c-c6e1-41cb-9df5-bb62f2a7a612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/i</value>
      <webElementGuid>ee613b25-a2ef-47fe-822e-04356fe9026f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
