<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_of_GCM-icons icon-first_page text-neutral_1d6a1f</name>
   <tag></tag>
   <elementGuidId>82a3eed5-ac19-4a39-8300-7bb7af622d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b12-$b2']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.GCM-icons.icon-first_page.text-neutral-6.fa-24.font-bold.fa.fa-flag.fa-1x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b6d96741-4966-4181-83c5-ad167e8d79a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GCM-icons icon-first_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x</value>
      <webElementGuid>be99d382-62e5-46cc-877c-ad0b2a55f946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-$b2&quot;)/i[@class=&quot;GCM-icons icon-first_page text-neutral-6 fa-24 font-bold fa fa-flag fa-1x&quot;]</value>
      <webElementGuid>c3f9d5e5-9385-42be-a295-4c35b2576bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b12-$b2']/i</value>
      <webElementGuid>fe840474-afb1-44e7-8798-0a0755a84f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/i</value>
      <webElementGuid>e6d4f2b0-ff20-46e9-b410-5f84fca17ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
