<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Imports_Tab</name>
   <tag></tag>
   <elementGuidId>1e579a4c-2e68-46f6-9043-4ffbb93d7b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@id, 'NavigationItemName_Expr') and (text() = 'Imports' or . = 'Imports')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-l2-25_1-NavigationItemName_Expr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NavigationItemName_Expr</value>
      <webElementGuid>f67fe627-b43b-48b8-abe7-608c558390c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imports</value>
      <webElementGuid>0d635d08-ef9a-4196-a21d-5442b552589d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='b5-b1-l2-25_1-NavigationItemName_Expr']</value>
      <webElementGuid>53773452-40f6-4056-a366-39a9e9deff90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-b1-l2-25_1-NavigationItemName_link']/span</value>
      <webElementGuid>fc1385e9-1f6f-4e7b-a369-40398fb7139a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/following::span[1]</value>
      <webElementGuid>b4dc2a9c-6c67-4012-a86d-93b296cbfbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/following::span[4]</value>
      <webElementGuid>3987a839-3805-408d-acff-567f2a407699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/preceding::span[1]</value>
      <webElementGuid>56aa5856-0150-458b-8b6d-9d0ebf7fea9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[3]/preceding::span[2]</value>
      <webElementGuid>10bc959b-5d41-4896-8078-b9fb93f6561a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imports']/parent::*</value>
      <webElementGuid>e1561f50-5b35-493f-86e0-a6e637814e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>5fc68249-4d80-4a35-805f-9035b468a9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'b5-b1-l2-25_1-NavigationItemName_Expr' and (text() = 'Imports' or . = 'Imports')]</value>
      <webElementGuid>dc9f168d-c40b-4559-8fe3-0a03ab9c9c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
