<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File_l1_0-51_1-Checkbox</name>
   <tag></tag>
   <elementGuidId>ee887ba6-626c-4379-b838-b8b6853a5fd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='l1_0-51_1-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l1_0-51_1-Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20431617-fffd-4dc1-a8c2-897b561cb31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1be5cc1c-4b04-4edc-a794-6c772b74a1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4b1d6eab-772d-41f2-9e57-d754c807b50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>l1_0-51_1-Checkbox</value>
      <webElementGuid>059e7854-cefe-4bae-a13e-78df0d5af009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l1_0-51_1-Checkbox&quot;)</value>
      <webElementGuid>df713bf6-bc14-4f8d-86d0-0e61d06f49db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='l1_0-51_1-Checkbox']</value>
      <webElementGuid>140b6cdb-5e4a-4bb7-a289-2c72ee9d2d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ResultsTable']/tbody/tr[2]/td/span/input</value>
      <webElementGuid>ea133c4c-3313-4cd7-9c8f-d4ba715087e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span/input</value>
      <webElementGuid>4d6bc0ec-f4fb-421a-a9a3-705e6076efdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'l1_0-51_1-Checkbox']</value>
      <webElementGuid>9f68d433-cc52-474c-8bdf-c33674e6973e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
