<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SMS_Confirm_Button</name>
   <tag></tag>
   <elementGuidId>c990ee67-05c4-4d6d-8124-b58a6cbcbabd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idSubmit_SAOTCC_Continue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idSubmit_SAOTCC_Continue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b1234c6-b5d8-4ba6-b38c-991ec50641e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6ad3cf66-5eae-4ebb-a096-478590035043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idSubmit_SAOTCC_Continue</value>
      <webElementGuid>f78610fc-7cac-4262-97ae-161828bf5232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>win-button button_primary button ext-button primary ext-primary</value>
      <webElementGuid>dccbd052-6281-43ee-90d8-bc55da6d6ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-event</name>
      <type>Main</type>
      <value>Signin_Submit</value>
      <webElementGuid>bcef3c13-2231-4a1f-8717-27e9822b89c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-trigger</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>947a2991-cf72-4687-a8b6-8b86ab2d1009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>307d6b3e-4dea-49da-8e32-80cf5d5902eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                attr: primaryButtonAttributes,
                externalCss: {
                    'button': true,
                    'primary': true },
                value: primaryButtonText() || str['CT_PWD_STR_SignIn_Button_Next'],
                hasFocus: focusOnPrimaryButton,
                click: svr.fEnableLivePreview ?  function() { } : primaryButton_onClick,
                clickBubble: !svr.fEnableLivePreview,
                enable: isPrimaryButtonEnabled,
                visible: isPrimaryButtonVisible,
                preventTabbing: primaryButtonPreventTabbing</value>
      <webElementGuid>c2a85e46-2b51-4623-992c-0778bd7bb5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verificar</value>
      <webElementGuid>45cfeb53-9f26-4556-a266-c39880e68052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-attached</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>51fb1ae9-1f09-448f-8826-a5b65d601bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idSubmit_SAOTCC_Continue&quot;)</value>
      <webElementGuid>dbaf5bb8-dab8-47f6-bfe7-3b3b872e50dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idSubmit_SAOTCC_Continue']</value>
      <webElementGuid>63a70475-864c-4085-94a9-6d80a70075ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[2]/div[2]/div/div[2]/div/div[6]/div/div/div/div/input</value>
      <webElementGuid>8b321920-f1ef-4201-ba49-5ca71ca7eacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input</value>
      <webElementGuid>50626848-04ed-4236-a7d4-96b5485ba6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'idSubmit_SAOTCC_Continue']</value>
      <webElementGuid>f3116528-21a4-4c38-afe2-82f85e0e7572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
